server:
  port: ${PORT}

  security:
    user:
      name: ${USERNAME}
      password: ${PASSWORD}

  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: main
          search-paths: "{application}"